# File: docker-compose.yml
version: '3.8'

services:
  servico-gestao:
    build: ./servico-gestao
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
    volumes:
      - ./servico-gestao:/app
      - /app/node_modules
    command: npm run dev

  servico-faturamento:
    build: ./microservices/servico-faturamento
    ports:
      - "3001:3001"
    environment:
      NODE_ENV: development
    volumes:
      - ./microservices/servico-faturamento:/app
      - /app/node_modules
    command: npm run dev

  servico-planos-ativos:
    build: ./microservices/servico-planos-ativos
    ports:
      - "3002:3002"
    environment:
      NODE_ENV: development
    volumes:
      - ./microservices/servico-planos-ativos:/app
      - /app/node_modules
    command: npm run dev

networks:
  default:
    driver: bridge